# apiVersion: apps/v1
# # what I want to create - a deployment
# kind: Deployment
# metadata:
#     # name of the deployment
#     name: nginx-deployment
#     labels:
#         app: nginx
# # specs for the deployment
# spec:
#     replicas: 1
#     selector:
#         matchLabels:
#             app: nginx
#     # blueprint for the pods
#     template:
#         metadata:
#             # labels to select/identify the deployment
#             labels:
#                 app: nginx
#         # specs for the pods
#         spec:
#             containers:
#             - name: nginx
#               image: nginx:1.16
#               ports:
#               - containerPort: 80
            
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
      - name: nodeapp
        image: stringsound/chat-api:alpine1.0.1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
spec:
  selector:
    app: chat-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
